### ISSUE TITLE
Support Libraries

### ISSUE THREAD

**Issue by Allosh87** [felixisto/NotABadPlayer-Android#1]
hi, thanks for sharing this but this isn't building with the latest support Libraries 28, so I changed back to 27.+. This builds and installs correctly but crashes on startup. Any help here?

**Comment by Allosh87** [comment]
Apparently, the problem is the support compat v28.0.0. It says 
No resource identifier for attribute: appComponentFactory

**Comment by felixisto** [comment]
@Allosh87 It builds and runs fine for me.
Tested this on:
Samsung phone running Android 8
HUAWEI phone running Android 5.1 (interface looks terrible but its functional)
HUAWEI table running Android 8

I think the gradle version of the
Take a look at this it might help you build the project https://github.com/android/android-ktx/issues/551#issuecomment-402826936
